### ISSUE TITLE
issue running aquatone 

### ISSUE THREAD

**Issue by soupnatzi** [michenriksen/aquatone#221]
everything works fine until this starts happening 

fatal error: concurrent map read and map write
goroutine 67859 [running]:
runtime.throw(0x8d9877, 0x21)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00791ab20 sp=0xc00791aaf0 pc=0x42be52
runtime.mapaccess2_faststr(0x846e00, 0xc00015a030, 0xc000e44cc0, 0x24, 0xc00791abf8, 0x2)
	/usr/local/go/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc00791ab90 sp=0xc00791ab20 pc=0x412609
github.com/michenriksen/aquatone/core.(*Session).GetPage(...)
	/Users/michael/go/src/github.com/michenriksen/aquatone/core/session.go:129
github.com/michenriksen/aquatone/agents.(*URLScreenshotter).OnURLResponsive(0xc00015a300, 0xc000e44cc0, 0x24)
	/Users/michael/go/src/github.com/michenriksen/aquatone/agents/url_screenshotter.go:43 +0x148 fp=0xc00791ac28 sp=0xc00791ab90 pc=0x7b6498
github.com/michenriksen/aquatone/agents.(*URLScreenshotter).OnURLResponsive-fm(0xc000e44cc0, 0x24)
	/Users/michael/go/src/github.com/michenriksen/aquatone/agents/url_screenshotter.go:41 +0x3e fp=0xc00791ac50 sp=0xc00791ac28 pc=0x7c223e

hoping someone has came across this issue and can help

**Comment by webx0** [comment]
Just ran into this issue on windows, seems like it was running to many threads (?) I'm trying -threads 4, seems to be working fine.. though it hasn't finished. Thought i'd post this before I forgot to post. Hopefully it works. Seems to be. good luck and wish me luck!

**Comment by soupnatzi** [comment]
i did not try to low the threads will try and add the results thanks for your feedback @webx0

**Comment by webx0** [comment]
> i did not try to lower the threads will try and add the results thanks for your feedback @webx0

also just figured out my second problem, edited it in my post, good luck!

**Comment by soupnatzi** [comment]
thanks @webx0 am on linux tho not windows but threads seems to fixed the issue i was running it on my script and it seemed to crap out when i ran it against alot of subdomains but setting the threads seemed to work.

**Comment by webx0** [comment]
> thanks @webx0 am on linux tho not windows but threads seems to fixed the issue i was running it on my script and it seemed to crap out when i ran it against alot of subdomains but setting the threads seemed to work.

nice, setting the threads lower worked for me aswell, but didn't work after like the 4th try.. weird.. but setting -http-timeout higher (10000 ms) fixed that issue aswell, just documenting my fixes just in case someone else has these types of issues

**Comment by L11R** [comment]
I fixed it in my fork: https://github.com/L11R/aquatone
Code definitely had an issue with concurrent map access.
