### ISSUE TITLE
binary hangs 

### ISSUE THREAD

**Issue by chppppp** [michenriksen/aquatone#234]
wow open issue #52! :D 

i am using the precompiled binary on a fresh kali 2020.1 box. running `aquatone domain.com` just hangs forever. appending `-debug` does nothing.

**Comment by chppppp** [comment]
I see this in GDB - 

```syscall.Syscall () at /usr/local/go/src/syscall/asm_linux_amd64.s:27
27      /usr/local/go/src/syscall/asm_linux_amd64.s: No such file or directory.
```

Perhaps this app requires some specific Go version????

**Comment by chppppp** [comment]
The latest binary release also hangs on a Fedora release 31 machine. 

Perhaps you could include system requirements for folks who want to use your software? The instructions of "download binary and add to PATH" seems outdated. Especially with 50+ open issues.

**Comment by chppppp** [comment]
The file it cant find is located at `/usr/lib/golang/src/syscall/asm_linux_amd64.s` on default Go installs.

**Comment by chppppp** [comment]
So oddly enough, I fixed my issue by removing golang from my system. Very weird!

**Comment by yeroc-sebrof** [comment]
I've also noticed the binary hangs

**Comment by yeroc-sebrof** [comment]
```
Thread 1 "aquatone" hit Temporary breakpoint 1, main.main () at /Users/michael/go/src/github.com/michenriksen/aquatone/main.go:46
warning: Source file is more recent than executable.
46	func main() {
(gdb) c
Continuing.
aquatone v1.7.0 started at 2020-04-01T02:55:05-07:00

[Detaching after vfork from child process 40110]
^C
Thread 1 "aquatone" received signal SIGINT, Interrupt.
runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:536
536	/usr/local/go/src/runtime/sys_linux_amd64.s: No such file or directory.
(gdb) where
#0  runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:536
#1  0x0000000000429c5b in runtime.futexsleep (addr=0xcce288 <runtime.m0+328>, val=0, ns=-1) at /usr/local/go/src/runtime/os_linux.go:46
#2  0x000000000040a381 in runtime.notesleep (n=0xcce288 <runtime.m0+328>) at /usr/local/go/src/runtime/lock_futex.go:151
#3  0x0000000000431961 in runtime.stopm () at /usr/local/go/src/runtime/proc.go:1936
#4  0x0000000000432aba in runtime.findrunnable (gp=0xc000024500, inheritTime=false) at /usr/local/go/src/runtime/proc.go:2399
#5  0x00000000004336dc in runtime.schedule () at /usr/local/go/src/runtime/proc.go:2525
#6  0x00000000004339f1 in runtime.park_m (gp=0xc000001380) at /usr/local/go/src/runtime/proc.go:2605
#7  0x0000000000455bdb in runtime.mcall () at /usr/local/go/src/runtime/asm_amd64.s:299
#8  0x0000000000455af9 in runtime.rt0_go () at /usr/local/go/src/runtime/asm_amd64.s:201
#9  0x0000000000000000 in ?? ()
(gdb) continue
Continuing.
^C
Thread 1 "aquatone" received signal SIGINT, Interrupt.
runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:536
536	in /usr/local/go/src/runtime/sys_linux_amd64.s
(gdb) where
#0  runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:536
#1  0x0000000000429c5b in runtime.futexsleep (addr=0xcce288 <runtime.m0+328>, val=0, ns=-1) at /usr/local/go/src/runtime/os_linux.go:46
#2  0x000000000040a381 in runtime.notesleep (n=0xcce288 <runtime.m0+328>) at /usr/local/go/src/runtime/lock_futex.go:151
#3  0x0000000000431961 in runtime.stopm () at /usr/local/go/src/runtime/proc.go:1936
#4  0x0000000000432aba in runtime.findrunnable (gp=0xc000026a00, inheritTime=false) at /usr/local/go/src/runtime/proc.go:2399
#5  0x00000000004336dc in runtime.schedule () at /usr/local/go/src/runtime/proc.go:2525
#6  0x00000000004339f1 in runtime.park_m (gp=0xc000060300) at /usr/local/go/src/runtime/proc.go:2605
#7  0x0000000000455bdb in runtime.mcall () at /usr/local/go/src/runtime/asm_amd64.s:299
#8  0x0000000000455af9 in runtime.rt0_go () at /usr/local/go/src/runtime/asm_amd64.s:201
#9  0x0000000000000000 in ?? ()
(gdb) c
Continuing.
```
