### ISSUE TITLE
Nameserver does not exist on domain does not fallback.

### ISSUE THREAD

**Issue by Kapulara** [michenriksen/aquatone#26]
Hey!

Loving the tool.

Something to note however: when a domain has a nameserver but the nameserver does not exist anymore, it doesn't use the fallback DNS ip's.

Or maybe it could ignore only the DNS that didn't function. And only use the 2 dns servers which actually returned something.

If that makes sense..

```
                           __
  ____ _____ ___  ______ _/ /_____  ____  ___
 / __ `/ __ `/ / / / __ `/ __/ __ \/ __ \/ _ \
/ /_/ / /_/ / /_/ / /_/ / /_/ /_/ / / / /  __/
\__,_/\__, /\__,_/\__,_/\__/\____/_/ /_/\___/
        /_/  discover v0.1.1 - by @michenriksen

Identifying nameservers for xxx... An unexpected error occurred: Resolv::ResolvError: DNS result has no information for dns3.xxx
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/resolv.rb:384:in `getaddress'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/domain.rb:20:in `block (2 levels) in nameservers'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/domain.rb:20:in `map'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/domain.rb:20:in `block in nameservers'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/domain.rb:16:in `times'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/domain.rb:16:in `nameservers'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:33:in `setup_resolver'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:16:in `execute!'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/lib/aquatone/command.rb:10:in `run'
/usr/local/rvm/gems/ruby-2.4.1/gems/aquatone-0.1.1/exe/aquatone-discover:129:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/bin/aquatone-discover:23:in `load'
/usr/local/rvm/gems/ruby-2.4.1/bin/aquatone-discover:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by michenriksen** [comment]
Hi there, thanks for reporting! Would you mind e-mailing me the domain you experienced the problem with for debugging? **michenriksen `at` neomailbox `dot` ch**

**Comment by securitybites** [comment]
Having this issue as well.

**Comment by securitybites** [comment]
Here is the error and domain I hit issues with:

~~~
Identifying nameservers for starbucks.com... An unexpected error occurred: Resolv::ResolvError: DNS result has no information for h4.nstld.com
/Users/hacker/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/resolv.rb:383:in `getaddress'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/domain.rb:20:in `block (2 levels) in nameservers'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/domain.rb:20:in `map'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/domain.rb:20:in `block in nameservers'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/domain.rb:16:in `times'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/domain.rb:16:in `nameservers'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/commands/discover.rb:33:in `setup_resolver'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/commands/discover.rb:16:in `execute!'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/lib/aquatone/command.rb:10:in `run'
/Users/hacker/.rvm/gems/ruby-2.2.0/gems/aquatone-0.4.0/exe/aquatone-discover:138:in `<top (required)>'
/Users/hacker/.rvm/gems/ruby-2.2.0/bin/aquatone-discover:23:in `load'
/Users/hacker/.rvm/gems/ruby-2.2.0/bin/aquatone-discover:23:in `<main>'
/Users/hacker/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/hacker/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
~~~

**Comment by Kapulara** [comment]
It expects that all nameservers exist when it found custom domains.
