### ISSUE TITLE
error and exit

### ISSUE THREAD

**Issue by notwhy** [michenriksen/aquatone#267]
Hi, i met this problem on my mac,which is the latest version of aquatone.
 cat 1.txt| aquatone -threads 4
```
goroutine 218464 [select]:
github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).AddWithContext(0xc00019a0e0, 0x157e200, 0xc0000ae020, 0x1d, 0xc00b76d630)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup/sizedwaitgroup.go:63 +0xc5
github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Add(...)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup/sizedwaitgroup.go:51
github.com/michenriksen/aquatone/agents.(*URLPageTitleExtractor).OnURLResponsive(0xc000140058, 0xc000eada20, 0x1d)
	/Users/michael/go/src/github.com/michenriksen/aquatone/agents/url_page_title_extractor.go:39 +0x1a2
reflect.Value.call(0x142e2a0, 0xc000138260, 0x13, 0x14cbb28, 0x4, 0xc000751900, 0x1, 0x1, 0xc00760d8b0, 0x142f6a0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x142e2a0, 0xc000138260, 0x13, 0xc000751900, 0x1, 0x1, 0xc000751900, 0x1, 0x1)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus.(*EventBus).doPublish(0xc00013c220, 0xc00013e690, 0x14d4a5b, 0xe, 0xc00760d8b0, 0x1, 0x1)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus/event_bus.go:158 +0xa8
github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus.(*EventBus).doPublishAsync(0xc00013c220, 0xc00013e690, 0x14d4a5b, 0xe, 0xc00760d8b0, 0x1, 0x1)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus/event_bus.go:166 +0xa1
created by github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus.(*EventBus).Publish
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus/event_bus.go:150 +0x22f

goroutine 218465 [select]:
github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).AddWithContext(0xc00019a0e0, 0x157e200, 0xc0000ae020, 0x1d, 0xc00b76d630)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup/sizedwaitgroup.go:63 +0xc5
github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Add(...)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/remeh/sizedwaitgroup/sizedwaitgroup.go:51
github.com/michenriksen/aquatone/agents.(*URLScreenshotter).OnURLResponsive(0xc00013e6c0, 0xc000eada20, 0x1d)
	/Users/michael/go/src/github.com/michenriksen/aquatone/agents/url_screenshotter.go:49 +0x1a2
reflect.Value.call(0x142e2a0, 0xc000138280, 0x13, 0x14cbb28, 0x4, 0xc00a00e980, 0x1, 0x1, 0xc00760d8b0, 0x142f6a0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x142e2a0, 0xc000138280, 0x13, 0xc00a00e980, 0x1, 0x1, 0xc00a00e980, 0x1, 0x1)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus.(*EventBus).doPublish(0xc00013c220, 0xc00013e6f0, 0x14d4a5b, 0xe, 0xc00760d8b0, 0x1, 0x1)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus/event_bus.go:158 +0xa8
github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus.(*EventBus).doPublishAsync(0xc00013c220, 0xc00013e6f0, 0x14d4a5b, 0xe, 0xc00760d8b0, 0x1, 0x1)
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus/event_bus.go:166 +0xa1
created by github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus.(*EventBus).Publish
	/Users/michael/go/src/github.com/michenriksen/aquatone/vendor/github.com/asaskevich/EventBus/event_bus.go:150 +0x22f
```

**Comment by fardeen-ahmed** [comment]
Hey there,
Try reinstalling go. These errors generally happen when go is not installed properly. If still persists, then comment back here.
This probably happens due to "go not installed properly" only.

If this helps you then cool, and not then comment here. i will try to resolve ASAP.

**Comment by notwhy** [comment]
Maybe I used too many threads or too many targets
