### ISSUE TITLE
adding key fails when keyfile doesn't exist

### ISSUE THREAD

**Issue by DannyCork** [michenriksen/aquatone#61]
- aquatone (0.5.0)
- CentOS Linux release 7.4.1708 (Core) 

Problems attempting to add an api key

```
$ aquatone-discover --set-key shodan xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:44:in `initialize': No such file or directory - /home/cccc/aquatone
/.keys.yml (Errno::ENOENT)
        from /usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:44:in `open'
        from /usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:44:in `write_key_store_file'
        from /usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:17:in `set'
        from /usr/local/share/gems/gems/aquatone-0.5.0/exe/aquatone-discover:63:in `block (2 levels) in <top (required)>'
        from /usr/share/ruby/optparse.rb:1364:in `call'
        from /usr/share/ruby/optparse.rb:1364:in `block in parse_in_order'
        from /usr/share/ruby/optparse.rb:1351:in `catch'
        from /usr/share/ruby/optparse.rb:1351:in `parse_in_order'
        from /usr/share/ruby/optparse.rb:1345:in `order!'
        from /usr/share/ruby/optparse.rb:1437:in `permute!'
        from /usr/share/ruby/optparse.rb:1459:in `parse!'
        from /usr/local/share/gems/gems/aquatone-0.5.0/exe/aquatone-discover:136:in `<top (required)>'
        from /usr/local/bin/aquatone-discover:23:in `load'
        from /usr/local/bin/aquatone-discover:23:in `<main>'
```

I then 

```
$ mkdir aquatone
$ touch aquatone/.keys.yml
```

and get a different error

```
$ aquatone-discover --set-key shodan xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:67:in `deserialize': undefined method `to_ruby' for false:FalseClass
 (NoMethodError)
        from /usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:37:in `read_key_store_file'
        from /usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:21:in `keys'
        from /usr/local/share/gems/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:15:in `set'
        from /usr/local/share/gems/gems/aquatone-0.5.0/exe/aquatone-discover:63:in `block (2 levels) in <top (required)>'
        from /usr/share/ruby/optparse.rb:1364:in `call'
        from /usr/share/ruby/optparse.rb:1364:in `block in parse_in_order'
        from /usr/share/ruby/optparse.rb:1351:in `catch'
        from /usr/share/ruby/optparse.rb:1351:in `parse_in_order'
        from /usr/share/ruby/optparse.rb:1345:in `order!'
        from /usr/share/ruby/optparse.rb:1437:in `permute!'
        from /usr/share/ruby/optparse.rb:1459:in `parse!'
        from /usr/local/share/gems/gems/aquatone-0.5.0/exe/aquatone-discover:136:in `<top (required)>'
        from /usr/local/bin/aquatone-discover:23:in `load'
        from /usr/local/bin/aquatone-discover:23:in `<main>'

```

**Comment by PatrikFehrenbach** [comment]
Hey @DannyCork 

I just had a similar issue, if you first 

```git clone https://github.com/michenriksen/aquatone.git``` 
and then do the set key it should work :-)

**Comment by Os3r3um** [comment]
@PatrikFehrenbach that does not actually solve the issue. 

```
/var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:67:in `deserialize': undefined method `to_ruby' for false:FalseClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:37:in `read_key_store_file'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:21:in `keys'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:15:in `set'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/exe/aquatone-discover:63:in `block (2 levels) in <top (required)>'
	from /usr/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
	from /usr/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/exe/aquatone-discover:136:in `<top (required)>'
	from /usr/local/bin/aquatone-discover:22:in `load'
	from /usr/local/bin/aquatone-discover:22:in `<main>'
```

It might be a ruby env problem as far the error message says something about 2.3.0 version while the Kali does have 2.3.2? I'm not a ruby dude anyway.
